server:
  port: 8091
spring:
  datasource:
    #<------H2-------------->
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/task_db;DB_CLOSE_ON_EXIT=FALSE;

  h2:
    console:
      enabled: true
      path: /h2