server:
  port: 8091
spring:
  datasource:
    #<------H2-------------->
    #platform: h2
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:~/task_db;DB_CLOSE_ON_EXIT=FALSE;

    #<------Postgres-------------->
    platform: postgresql
    driverClassName: org.postgresql.Driver
    #<----- without Ðš8s ---->
    url: jdbc:postgresql://localhost:5432/task_db DB_CLOSE_DELAY=-1; DB_CLOSE_ON_EXIT=FALSE
    username: postgres
    password: postgres

    initialization-mode: always

  #h2:
   # console:
    #  enabled: true
     # path: /h2
